name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

permissions:
  id-token: write  
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE }} 
          aws-region: eu-north-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt 

      - name: Terraform Plan
        env: 
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}

        run: terraform plan -lock=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
        run: |
          terraform apply -auto-approve -lock=false